vim.wo.number = true --Make line numbers default
vim.o.relativenumber = true
vim.o.clipboard = "unnamedplus" --Sync clipboard between OS and Neovim
vim.o.wrap = false
vim.o.linebreak = true
vim.o.mouse = "a"
vim.o.autoindent = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.expandtab = true
vim.o.scrolloff = 4
vim.o.sidescrolloff = 8
vim.o.cursorline = false
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.smartindent = true
vim.o.swapfile = false
vim.o.showtabline = 2
vim.o.backspace = "indent,eol,start"
vim.o.laststatus = 3
vim.o.cmdheight = 0
